version: '3'
services: #(where container list goes)
  mariadb:
    build: 
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - docker_inside_network
    volumes:
      - /home/thi-nguy/data/mariadb-data:/var/lib/mysql/
    env_file:
      - ".env"
    expose:
      - 3306
    restart: always

  wordpress:
    build: 
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - docker_inside_network
    # ports:
    #   - 9000:9000
    expose:
      - 9000
    env_file:
      - ".env"
    links:
      - mariadb
    volumes: # source-host: destination-container
      - /home/thi-nguy/data/wordpress-data:/var/www/html
    restart: always

  nginx: #name we want to set to our container, if not specified, it will give a random name
    build:  # Do khong dung image tai tren Docker hub nen ta phai build image truoc
      context: ./requirements/nginx/ #go to this directory, look for and run Dockerfile
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    networks:
      - docker_inside_network
    ports:
      - 443:443 # host:container
    expose:
      - 443
    volumes: #name of volume : link to volume at host machine
      # - nginx:/etc/nginx/conf.d
      - /home/thi-nguy/data/wordpress-data:/var/www/html
    links:
      - wordpress
    restart: always



networks:
  docker_inside_network:
    driver: bridge

# volumes:
#   wordpress-vol:
#     # # name: wordpress-data
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/thi-nguy/data/wordpress-data
#   mariadb-vol:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: /home/thi-nguy/data/mariadb-data
